export const clerkAppearance = {
  variables: {
    colorPrimary: '#E63946',
    colorText: '#0f172a',
    colorTextSecondary: '#64748b',
    colorBackground: '#ffffff',
    colorInputBackground: '#f8fafc',
    colorInputText: '#0f172a',
    borderRadius: '0.9rem',
  },
  elements: {
    rootBox: 'w-full min-w-0 max-w-full',
    cardBox: 'w-full min-w-0 max-w-full shadow-none',
    card: 'w-full min-w-0 max-w-full border-0 !p-0 shadow-none',
    main: 'w-full min-w-0 max-w-full',
    header: 'w-full min-w-0',
    headerTitle: 'text-slate-950 font-black text-xl sm:text-2xl xl:text-xl',
    headerSubtitle: 'text-slate-500 text-xs sm:text-sm xl:text-xs',
    socialButtonsBlockButton: 'w-full min-w-0 min-h-11 border-slate-200 hover:bg-slate-50 transition rounded-xl',
    socialButtonsBlockButtonText: 'truncate',
    dividerRow: 'w-full min-w-0',
    form: 'w-full min-w-0 max-w-full',
    formFieldRow: 'w-full min-w-0',
    formField: 'w-full min-w-0',
    formFieldInput: 'w-full min-w-0 max-w-full min-h-11 rounded-xl border-slate-200 bg-slate-50 focus:bg-white focus:border-[#E63946]',
    formFieldLabel: 'text-slate-700',
    formButtonPrimary: 'w-full min-w-0 min-h-11 bg-[#E63946] hover:bg-[#D90429] shadow-none rounded-xl font-bold',
    footer: 'w-full min-w-0',
    footerAction: 'w-full min-w-0',
    footerActionLink: 'text-[#E63946] hover:text-[#D90429] font-bold',
    identityPreview: 'w-full min-w-0 max-w-full',
    identityPreviewText: 'min-w-0 truncate',
  },
} as const;
